{% set name = "sott" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sott-{{ version }}.tar.gz
  sha256: 245fcfc475c3e25431f9cfde1941423f1b134f4d838e36d97e9a7fa34a41f997

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy

test:
  imports:
    - sott
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kanglcn/sott
  summary: Simple Offset Tracking Tool
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kanglcn
